# Generated by Django 4.1.3 on 2022-12-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_corredor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corredor',
            new_name='Corredores',
        ),
    ]
