# Generated by Django 4.1.3 on 2022-12-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0003_rename_corredor_corredores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corredores',
            new_name='Corredor',
        ),
    ]
