# Generated by Django 4.1.3 on 2022-12-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0004_rename_corredores_corredor'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
