# Generated by Django 4.1.3 on 2022-12-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0005_corredor_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
