# Generated by Django 4.1.3 on 2022-12-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0006_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fechaNacimiento', models.CharField(max_length=50)),
            ],
        ),
    ]
