# Generated by Django 4.1.3 on 2022-12-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0010_corredor_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paisOrigen', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('chasis', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=50)),
                ('neumaticos', models.CharField(max_length=50)),
                ('debut', models.IntegerField()),
                ('campeonatos', models.IntegerField()),
            ],
        ),
    ]
