# Generated by Django 4.1.3 on 2022-12-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0013_piloto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
