# Generated by Django 4.1.3 on 2023-01-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0015_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
    ]
