# Generated by Django 4.1.3 on 2023-01-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0016_remove_mensaje_leido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mensaje',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='a_quehora',
            new_name='horario',
        ),
    ]
