# Generated by Django 4.1.3 on 2022-12-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0007_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
