# Generated by Django 4.1.3 on 2022-12-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0009_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='equipo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
