# Generated by Django 4.1.3 on 2022-12-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0011_equipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corredor',
            new_name='Piloto',
        ),
    ]
